---
- name: "SCORED | 2.2.1 | PATCH | (L1) Ensure 'Access Credential Manager as a trusted caller' is set to 'No One'"
  win_user_right:
    name: SeTrustedCredManAccessPrivilege
    users:
    action: set
  when: rule_2_2_1
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.1
    - patch

- name: "SCORED | 2.2.2 | PATCH | (L1) Ensure 'Access this computer from the network' is set to 'Administrators, Authenticated Users, ENTERPRISE DOMAIN CONTROLLERS' (DC only)"
  win_user_right:
    name: SeNetworkLogonRight
    users:
      - Administrators
      - Authenticated Users
      - ENTERPRISE DOMAIN CONTROLLERS
    action: set
  when:
    - rule_2_2_2
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller1
    - rule_2.2.2
    - patch

- name: "SCORED | 2.2.3 | PATCH | (L1) Ensure 'Access this computer from the network' is set to 'Administrators, Authenticated Users' (MS only)"
  win_user_right:
    name: SeNetworkLogonRight
    users:
      - Administrators
      - Authenticated Users
    action: set
  when:
    - rule_2_2_3
    - not ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-memberserver
    - rule_2.2.3
    - patch

- name: "SCORED | 2.2.4 | PATCH | (L1) Ensure 'Act as part of the operating system' is set to 'No One'"
  win_user_right:
    name: SeTcbPrivilege
    users:
    action: set
  when: rule_2_2_4
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.4
    - patch

- name: "SCORED | 2.2.5 | PATCH | (L1) Ensure 'Add workstations to domain' is set to 'Administrators' (DC only)"
  win_user_right:
      name: SeMachineAccountPrivilege
      users: Administrators
      action: set
  when:
    - rule_2_2_5
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller
    - rule_2.2.5
    - patch

- name: "SCORED | 2.2.6 | PATCH | (L1) Ensure 'Adjust memory quotas for a process' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeIncreaseQuotaPrivilege
    users:
    - Administrators
    - Local Service
    - Network Service
    action: set
  when: rule_2_2_6
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.6
    - patch

- name: "SCORED | 2.2.7 | PATCH | (L1) Ensure 'Allow log on locally' is set to 'Administrators'"
  win_user_right:
    name: SeInteractiveLogonRight
    users:
    - Administrators
    action: set
  when: rule_2_2_7
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.7
    - patch

- name: "SCORED | 2.2.8 | PATCH | (L1) Ensure 'Allow log on through Remote Desktop Services' is set to 'Administrators' (DC only)"
  win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
    - Administrators
    action: set
  when:
    - rule_2_2_8
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller
    - rule_2.2.8
    - patch

- name: "SCORED | 2.2.9 | PATCH | (L1) Ensure 'Allow log on through Remote Desktop Services' is set to 'Administrators, Remote Desktop Users' (MS only)"
  win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
    - Administrators
    - Remote Desktop Users
    action: set
  when:
    - rule_2_2_9
    - not ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-memberserver
    - rule_2.2.9
    - patch

- name: "SCORED | 2.2.10 | PATCH | (L1) Ensure 'Back up files and directories' is set to 'Administrators'"
  win_user_right:
    name: SeBackupPrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_10
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.10
    - patch

- name: "SCORED | 2.2.11 | PATCH | (L1) Ensure 'Change the system time' is set to 'Administrators, LOCAL SERVICE'"
  win_user_right:
    name: SeSystemTimePrivilege
    users:
    - Administrators
    - Local Service
    action: set
  when: rule_2_2_11
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.11
    - patch

- name: "SCORED | 2.2.12 | PATCH | (L1) Ensure 'Change the time zone' is set to 'Administrators, LOCAL SERVICE'"
  win_user_right:
    name: SeTimeZonePrivilege
    users:
    - Administrators
    - Local Service
    action: set
  when: rule_2_2_12
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.12
    - patch

- name: "SCORED | 2.2.13 | PATCH | (L1) Ensure 'Create a pagefile' is set to 'Administrators'"
  win_user_right:
    name: SeCreatePagefilePrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_13
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.13
    - patch

- name: "SCORED | 2.2.14 | PATCH | (L1) Ensure 'Create a token object' is set to 'No One'"
  win_user_right:
    name: SeCreateTokenPrivilege
    users:
    action: set
  when: rule_2_2_14
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.14
    - patch

- name: "SCORED | 2.2.15 | PATCH | (L1) Ensure 'Create global objects' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE'"
  win_user_right:
    name: SeCreateGlobalPrivilege
    users:
    - Administrators
    - Local Service
    - Network Service
    - Service
    action: set
  when: rule_2_2_15
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.15
    - patch

- name: "SCORED | 2.2.16 | PATCH | (L1) Ensure 'Create permanent shared objects' is set to 'No One'"
  win_user_right:
    name: SeCreatePermanentPrivilege
    users:
    action: set
  when: rule_2_2_16
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.16
    - patch

- name: "SCORED | 2.2.17 | PATCH | (L1) Ensure 'Create symbolic links' is set to 'Administrators' (DC only)"
  win_user_right:
    name: SeCreateSymbolicLinkPrivilege
    users:
    - Administrators
    action: set
  when:
    - rule_2_2_17
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller
    - rule_2.2.17
    - patch

- name: "SCORED | 2.2.18 | PATCH | (L1) Ensure 'Create symbolic links' is set to 'Administrators, NT VIRTUAL MACHINE\Virtual Machines' (MS only)"
  win_user_right:
    name: SeCreateSymbolicLinkPrivilege
    users:
    - Administrators
    - NT VIRTUAL MACHINE\Virtual Machines
    action: set
  when:
    - rule_2_2_18
    - ansible_windows_domain_role == "Member server"
  tags:
    - level1-memberserver
    - rule_2.2.18
    - patch

- name: "SCORED | 2.2.19 | PATCH | (L1) Ensure 'Debug programs' is set to 'Administrators'"
  win_user_right:
    name: SeDebugPrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_19
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.19
    - patch

     #Limiting hardening to only include the Guests group, since Local Account access will still be needed for non-domain-joined nodes
- name: "SCORED | 2.2.20 | PATCH | (L1) Ensure 'Deny access to this computer from the network' to include 'Guests' (DC only)"
  win_user_right:
    name: SeDenyNetworkLogonRight
    users:
    - Guests
    action: set
  when: 
    - rule_2_2_20
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller
    - rule_2.2.20
    - patch

- name: "SCORED | 2.2.21 | PATCH | (L1) Ensure 'Deny access to this computer from the network' to include 'Guests, Local account and member of Administrators group' (MS only)"
  win_user_right:
    name: SeDenyNetworkLogonRight
    users:
    - Guests
    #- Local Account
    #- Administrators
    action: set
  when: 
    - rule_2_2_21
    - ansible_windows_domain_member
  tags:
    - level1-memberserver
    - rule_2.2.21
    - patch

- name: "SCORED | 2.2.22 | PATCH | (L1) Ensure 'Deny log on as a batch job' to include 'Guests'"
  win_user_right:
    name: SeDenyBatchLogonRight
    users:
    - Guests
    action: set
  when: rule_2_2_22
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.22
    - patch

- name: "SCORED | 2.2.23 | PATCH | (L1) Ensure 'Deny log on as a service' to include 'Guests'"
  win_user_right:
    name: SeDenyServiceLogonRight
    users:
    - Guests
    action: set
  when: rule_2_2_23
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.23
    - patch

- name: "SCORED | 2.2.24 | PATCH | (L1) Ensure 'Deny log on locally' to include 'Guests'"
  win_user_right:
      name: SeDenyInteractiveLogonRight
      users:
      - Guests
      action: set
  when: rule_2_2_24
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.24
    - patch

- name: "SCORED | 2.2.25 | PATCH | (L1) Ensure 'Deny log on through Remote Desktop Services' to include 'Guests' (DC only)"
  win_user_right:
    name: SeDenyRemoteInteractiveLogonRight
    users:
    - Guests
    #- Local Account
    action: set
  when:
    - rule_2_2_25
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller
    - rule_2.2.25
    - patch

- name: "SCORED | 2.2.26 | PATCH | (L1) Ensure 'Deny log on through Remote Desktop Services' is set to 'Guests, Local account' (MS only)"
  win_user_right:
    name: SeDenyRemoteInteractiveLogonRight
    users:
    - Guests
    #- Local Account
    action: set
  when:
    - rule_2_2_26
    - ansible_windows_domain_member
  tags:
    - level1-memberserver
    - rule_2.2.26
    - patch

- name: "SCORED | 2.2.27 | PATCH | (L1) Ensure 'Enable computer and user accounts to be trusted for delegation' is set to 'Administrators' (DC only)"
  win_user_right:
    name: SeEnableDelegationPrivilege
    users: Administrators
    action: set
  when:
    - rule_2_2_27
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller
    - rule_2.2.27
    - patch

- name: "SCORED | 2.2.28 | PATCH | (L1) Ensure 'Enable computer and user accounts to be trusted for delegation' is set to 'No One' (MS only)"
  win_user_right:
    name: SeEnableDelegationPrivilege
    users: 
    action: set
  when:
    - rule_2_2_28
    - ansible_windows_domain_member
  tags:
    - level1-memberserver
    - rule_2.2.28
    - patch

- name: "SCORED | 2.2.29 | PATCH | (L1) Ensure 'Force shutdown from a remote system' is set to 'Administrators'"
  win_user_right:
      name: SeRemoteShutdownPrivilege
      users:
      - Administrators
      action: set
  when: rule_2_2_29
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.29
    - patch

- name: "SCORED | 2.2.30 | PATCH | (L1) Ensure 'Generate security audits' is set to 'LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeAuditPrivilege
    users:
    - Local Service
    - Network Service
    action: set
  when: rule_2_2_30
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.30
    - patch

- name: "SCORED | 2.2.31 | PATCH | (L1) Ensure 'Impersonate a client after authentication' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE' (DC only)"
  win_user_right:
    name: SeImpersonatePrivilege
    users:
    - Administrators
    - Local Service
    - Network Service
    - Service
    action: set
  when:
    - rule_2_2_31
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller
    - rule_2.2.31
    - patch

- name: "SCORED | 2.2.32 | PATCH | (L1) Ensure 'Impersonate a client after authentication' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE' and (when the Web Server (IIS) Role with Web Services Role Service is installed) 'IIS_IUSRS' (MS only)"
  win_user_right:
    name: SeImpersonatePrivilege
    users:
    - Administrators
    - IIS_IUSRS
    - Local Service
    - Network Service
    - Service
    action: set
  when:
    - rule_2_2_32
    - ansible_windows_domain_member
  tags:
    - level1-memberserver
    - rule_2.2.32
    - patch

- name: "SCORED | 2.2.33 | PATCH | (L1) Ensure 'Increase scheduling priority' is set to 'Administrators'"
  win_user_right:
    name: SeIncreaseBasePriorityPrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_33
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.33
    - patch

- name: "SCORED | 2.2.34 | PATCH | (L1) Ensure 'Load and unload device drivers' is set to 'Administrators'"
  win_user_right:
    name: SeLoadDriverPrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_34
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.34
    - patch

- name: "SCORED | 2.2.35 | PATCH | (L1) Ensure 'Lock pages in memory' is set to 'No One'"
  win_user_right:
    name: SeLockMemoryPrivilege
    users:
    action: set
  when: rule_2_2_35
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.35
    - patch

- name: "SCORED | 2.2.36 | PATCH | (L2) Ensure 'Log on as a batch job' is set to 'Administrators' (DC Only)"
  win_user_right:
    name: SeBatchLogonRight
    users: Administrators
    action: set
  when:
    - rule_2_2_36
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level2-domaincontroller
    - rule_2.2.36
    - patch

- name: "SCORED | 2.2.37 (DC) & 2.2.38 (MS) | PATCH | (L1) Ensure 'Manage auditing and security log' is set to 'Administrators' and (when Exchange is running in the environment) 'Exchange Servers'"
  win_user_right:
    name: SeSecurityPrivilege
    users:
    - Administrators
    action: set
  when:
    - rule_2_2_37 or rule_2_2_38
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.37
    - rule_2.2.38
    - patch

- name: "SCORED | 2.2.39 | PATCH | (L1) Ensure 'Modify an object label' is set to 'No One'"
  win_user_right:
    name: SeReLabelPrivilege
    users:
    action: set
  when: rule_2_2_39
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.39
    - patch

- name: "SCORED | 2.2.40 | PATCH | (L1) Ensure 'Modify firmware environment values' is set to 'Administrators'"
  win_user_right:
    name: SeSystemEnvironmentPrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_40
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.40
    - patch

- name: "SCORED | 2.2.41 | PATCH | (L1) Ensure 'Perform volume maintenance tasks' is set to 'Administrators'"
  win_user_right:
    name: SeManageVolumePrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_41
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.41
    - patch

- name: "SCORED | 2.2.42 | PATCH | (L1) Ensure 'Profile single process' is set to 'Administrators'"
  win_user_right:
    name: SeProfileSingleProcessPrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_42
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.42
    - patch

- name: "SCORED | 2.2.43 | PATCH | (L1) Ensure 'Profile system performance' is set to 'Administrators, NT SERVICE\WdiServiceHost'"
  win_user_right:
    name: SeSystemProfilePrivilege
    users:
    - Administrators
    - NT SERVICE\WdiServiceHost
    action: set
  when: rule_2_2_43
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.43
    - patch

- name: "SCORED | 2.2.44 | PATCH | (L1) Ensure 'Replace a process level token' is set to 'LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeAssignPrimaryTokenPrivilege
    users:
    - LOCAL SERVICE
    - NETWORK SERVICE
    action: set
  when: rule_2_2_44
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.44
    - patch

- name: "SCORED | 2.2.45 | PATCH | (L1) Ensure 'Restore files and directories' is set to 'Administrators'"
  win_user_right:
    name: SeRestorePrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_45
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.45
    - patch

- name: "SCORED | 2.2.46 | PATCH | (L1) Ensure 'Shut down the system' is set to 'Administrators'"
  win_user_right:
    name: SeShutdownPrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_46
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.46
    - patch

- name: "SCORED | 2.2.47 | PATCH | (L1) Ensure 'Synchronize directory service data' is set to 'No One' (DC only)"
  win_user_right:
    name: SeSyncAgentPrivilege
    users:
    action: set
  when:
    - rule_2_2_47
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level1-domaincontroller
    - rule_2.2.47
    - patch

- name: "SCORED | 2.2.48 | PATCH | (L1) Ensure 'Take ownership of files or other objects' is set to 'Administrators'"
  win_user_right:
    name: SeTakeOwnershipPrivilege
    users:
    - Administrators
    action: set
  when: rule_2_2_48
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_2.2.48
    - patch